### ISSUE TITLE
HTTP 500 if URL contains %E4

### ISSUE THREAD

**Issue by rjoonas** [reaktor/serve-static-git#1]
If I fire a request using an URL that contains `%E4`, a `decodeURIComponent` call inside the serve-index package ([index.js:113](https://github.com/expressjs/serve-index/blob/fcad6767c022d07fc50d0d6f3c97bec2171b2619/index.js#L113)) throws `URIError: URI malformed` and serve-static-git serves HTTP 500 through the default error handler.

**Comment by rjoonas** [comment]
Submitted a PR upstream: https://github.com/expressjs/serve-index/pull/85

**Comment by mpeltonen** [comment]
Fixed in Express.
